# Generated by Django 5.1.5 on 2025-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'success'), ('FAILED', 'failed'), ('REVERSED', 'reversed'), ('PROCESSED', 'processing')], default='COMPLETED', max_length=20),
        ),
    ]
