# Generated by Django 5.1.5 on 2025-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('OVERDUE', 'Overdue')], default='PROCESSED', max_length=20),
        ),
    ]
