# Generated by Django 5.1.5 on 2025-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'success'), ('FAILED', 'failed'), ('REVERSED', 'reversed'), ('PROCESSED', 'processing')], default='PROCESSED', max_length=20),
        ),
    ]
