# Generated by Django 5.1.5 on 2025-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PROCESSED', max_length=20),
        ),
    ]
