# Generated by Django 5.1.5 on 2025-02-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('specialization', models.CharField(max_length=255)),
                ('skills', models.JSONField(default=list)),
                ('projects', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
