# Generated by Django 5.1.5 on 2025-02-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_writerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
