# Generated by Django 5.1.5 on 2025-02-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paystack_reference',
        ),
    ]
